/**
 * i18n Configuration
 * Auto-generated by Auto-i18n
 */

import { createContext, useContext, useState, ReactNode } from 'react';

// Supported locales
export const locales = ["en","pt"] as const;
export type Locale = typeof locales[number];

// Default locale
export const defaultLocale: Locale = 'en';

// Namespaces
export const namespaces = ["jobsubmitform","joblist","jobcard"] as const;
export type Namespace = typeof namespaces[number];

// Translation type
type TranslationKey = string;
type Translations = Record<TranslationKey, string>;
type LocaleTranslations = Record<Namespace, Translations>;

// Context
interface I18nContextType {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (namespace: Namespace) => (key: string) => string;
}

const I18nContext = createContext<I18nContextType | null>(null);

// Translation cache
const translationCache: Partial<Record<Locale, LocaleTranslations>> = {};

// Load translations for a locale
async function loadTranslations(locale: Locale): Promise<LocaleTranslations> {
  if (translationCache[locale]) {
    return translationCache[locale]!;
  }
  
  const translations: LocaleTranslations = {} as LocaleTranslations;
  
  for (const namespace of namespaces) {
    try {
      const module = await import(`./locales/${locale}/${namespace}.json`);
      translations[namespace] = module.default || module;
    } catch {
      console.warn(`Missing translations: ${locale}/${namespace}`);
      translations[namespace] = {};
    }
  }
  
  translationCache[locale] = translations;
  return translations;
}

// Provider component
interface I18nProviderProps {
  children: ReactNode;
  initialLocale?: Locale;
}

export function I18nProvider({ children, initialLocale = defaultLocale }: I18nProviderProps) {
  const [locale, setLocale] = useState<Locale>(initialLocale);
  const [translations, setTranslations] = useState<LocaleTranslations | null>(null);
  
  // Load translations on locale change
  useState(() => {
    loadTranslations(locale).then(setTranslations);
  });
  
  const t = (namespace: Namespace) => (key: string): string => {
    if (!translations) return key;
    return translations[namespace]?.[key] || key;
  };
  
  return (
    <I18nContext.Provider value={{ locale, setLocale, t }}>
      {children}
    </I18nContext.Provider>
  );
}

// Hook for using translations
export function useTranslations(namespace: Namespace) {
  const context = useContext(I18nContext);
  
  if (!context) {
    // Fallback for components outside provider
    return (key: string) => key;
  }
  
  return context.t(namespace);
}

// Hook for locale management
export function useLocale() {
  const context = useContext(I18nContext);
  
  if (!context) {
    return {
      locale: defaultLocale,
      setLocale: () => {},
      locales,
    };
  }
  
  return {
    locale: context.locale,
    setLocale: context.setLocale,
    locales,
  };
}

// Utility to change locale
export function setLocale(locale: Locale) {
  if (typeof window !== 'undefined') {
    localStorage.setItem('locale', locale);
    window.location.reload();
  }
}

// Get current locale
export function getLocale(): Locale {
  if (typeof window !== 'undefined') {
    const stored = localStorage.getItem('locale') as Locale;
    if (stored && locales.includes(stored)) {
      return stored;
    }
  }
  return defaultLocale;
}
